"""Add due_in column to Deadline table

Revision ID: f43c8babcf36
Revises: bbc121983af8
Create Date: 2024-03-31 18:29:01.171848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43c8babcf36'
down_revision = 'bbc121983af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.drop_column('due_in')
        batch_op.drop_column('overdue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overdue', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('due_in', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
